version: 2
updates:
  # python scratchpad
  - package-ecosystem: "pip"
    directory: "/scratchpad"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      scratchpad:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2020 - python
  - package-ecosystem: "pip"
    directory: "/2020"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      aoc2020:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2021 - python
  - package-ecosystem: "pip"
    directory: "/2021"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      aoc2021:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2022 - python
  - package-ecosystem: "pip"
    directory: "/2022"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      aoc2021:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2023 - rust
  - package-ecosystem: "cargo"
    directory: "/2023/aoc2023"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      aoc2023:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
