version: 2
updates:
  # GH Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # python scratchpad
  - package-ecosystem: "pip"
    directory: "/scratchpad"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      scratchpad:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
