default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [-m]
        exclude: ^helm/templates/
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.9.0"
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0"
    hooks:
      - id: sync_with_poetry
        args: [] # optional args
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.2.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v2.3.0"
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/pycqa/docformatter
    rev: "v1.5.0"
    hooks:
      - id: docformatter
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        types: [markdown]
