name: pre-commit checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PIP_CACHE_DIR: /tmp/pip-cache-dir
  PYTHON_VERSION: "3.11"

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
